/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package src;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Mphstar
 */
public class ChartCekBarangTerlaris extends javax.swing.JPanel {

    /** Creates new form ChartCekStokBarang */
    public ChartCekBarangTerlaris() {
        initComponents();
        buatChart();
    }
    
    public void buatChart(){
        try {
            Connection conn = auth.Koneksi.configDB();
            String sql = "SELECT SUM(detail_barang.jumlah), barang.id_barang, "
                    + "barang.nama FROM detail_barang "
                    + "JOIN barang ON detail_barang.id_barang = barang.id_barang "
                    + "GROUP BY id_barang ORDER BY SUM(detail_barang.jumlah) DESC "
                    + "LIMIT 7";
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery(sql);
            DefaultCategoryDataset obj = new DefaultCategoryDataset();
            while(rs.next()){
                
                obj.setValue(Integer.parseInt(rs.getString(1)), rs.getString(3), rs.getString(2));
                JFreeChart chart = ChartFactory.createBarChart3D("Barang Terlaris", "Nama Barang", "Jumlah terjual", obj);
                CategoryPlot plot = chart.getCategoryPlot();
                plot.setRangeGridlinePaint(Color.black);
                ChartPanel hadeh = new ChartPanel(chart);
                hadeh.setSize(400, 300);
                this.add(hadeh);
            }
            
        } catch (Exception e) {
            DefaultCategoryDataset obj = new DefaultCategoryDataset();
            obj.setValue(10, "kosong", "kosong");
                JFreeChart chart = ChartFactory.createBarChart3D("Stok Barang Terlaris", "Nama Barang", "Jumlah Terjual", obj);
                CategoryPlot plot = chart.getCategoryPlot();
                plot.setRangeGridlinePaint(Color.black);
                ChartPanel hadeh = new ChartPanel(chart);
                hadeh.setSize(400, 300);
                this.add(hadeh);
        }
        
        
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(400, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 361, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 304, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
