/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.UIManager;

/**
 *
 * @author Mphstar
 */
public class Detail_Users extends javax.swing.JDialog {

    /**
     * Creates new form Detail_Users
     */
    
    public void UI(){
        //setUI(new ModernScrollBarUI());
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()){
                if ("Windows".equals(info.getName())){
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception e) {
            e.getMessage();
        }
    }
    
    public Detail_Users(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.getRootPane().setOpaque(false);
        this.getContentPane ().setBackground (new Color (0, 0, 0, 0));
        this.setBackground (new Color (0, 0, 0, 0));
        
        txt_roles.setSelectedItem(null);
        txt_roles.setBackground(Color.WHITE);
        id_akun();
        roles();
    }
    
    int konfirm;
    public void select(int konfirm){
        if ( konfirm == 0 ){
         
            txt_tambah.setVisible(true);
            btn_tambah.setVisible(true);
            
            txt_ubah.setVisible(false);
            btn_ubah.setVisible(false);
            txt_hapus.setVisible(false);
            btn_hapus.setVisible(false);
        } else if ( konfirm == 1 ){
            txt_tambah.setVisible(false);
            btn_tambah.setVisible(false);
            
            txt_ubah.setVisible(true);
            btn_ubah.setVisible(true);
            txt_hapus.setVisible(true);
            btn_hapus.setVisible(true);
       
        } else {
            
        }
    }
    
    public void show(String user, String pw, String nama, String email, String roles, String alamat, String nohp, String jeniskelamin, String pilih_user){
        this.txt_username.setText(user);
        this.txt_password.setText(pw);
        this.txt_nama.setText(nama);
        this.txt_email.setText(email);
        this.txt_roles.setSelectedItem(roles);
        this.txt_alamat.setText(alamat);
        this.txt_hp.setText(nohp);
        this.jenis_kelamin = jeniskelamin;
        
        if ( jeniskelamin.equals("Laki laki")){
            lakilaki.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tick_box_enable_30px.png")));
            perempuan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tick_box_disable_26px.png")));

        } else {
            lakilaki.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tick_box_disable_26px.png")));
            perempuan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tick_box_enable_30px.png")));

        }
        
        this.select_user = pilih_user;
        
    }
 
        public void roles(){
        try {
            String sql = "SELECT * FROM roles";
            Connection conn = auth.Koneksi.configDB();
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery(sql);
            while (rs.next()){
                txt_roles.addItem(rs.getString("jenis_roles"));
            }
        } catch (Exception e) {
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        txt_email = new javax.swing.JTextField();
        txt_alamat = new javax.swing.JTextField();
        txt_password = new javax.swing.JTextField();
        box_username4 = new javax.swing.JLabel();
        UI();
        txt_roles = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        box_username3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lakilaki = new javax.swing.JCheckBox();
        txt_hp = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        box_username6 = new javax.swing.JLabel();
        perempuan = new javax.swing.JCheckBox();
        box_username2 = new javax.swing.JLabel();
        box_id = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txt_hapus = new javax.swing.JLabel();
        btn_hapus = new javax.swing.JLabel();
        txt_ubah = new javax.swing.JLabel();
        btn_ubah = new javax.swing.JLabel();
        txt_tambah = new javax.swing.JLabel();
        btn_tambah = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        box_username5 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Toko SA");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Images/icon.png")).getImage());
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setForeground(new java.awt.Color(102, 102, 102));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 420, 1));

        txt_email.setBackground(new java.awt.Color(247, 247, 247));
        txt_email.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        txt_email.setBorder(null);
        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });
        txt_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_emailKeyPressed(evt);
            }
        });
        getContentPane().add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 170, 30));

        txt_alamat.setBackground(new java.awt.Color(247, 247, 247));
        txt_alamat.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        txt_alamat.setBorder(null);
        txt_alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_alamatActionPerformed(evt);
            }
        });
        txt_alamat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_alamatKeyPressed(evt);
            }
        });
        getContentPane().add(txt_alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 170, 30));

        txt_password.setBackground(new java.awt.Color(247, 247, 247));
        txt_password.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        txt_password.setBorder(null);
        txt_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passwordActionPerformed(evt);
            }
        });
        txt_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_passwordKeyPressed(evt);
            }
        });
        getContentPane().add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 170, 30));

        box_username4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Rounded TextBox.png"))); // NOI18N
        getContentPane().add(box_username4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 210, 50));

        txt_roles.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txt_roles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_rolesMouseClicked(evt);
            }
        });
        getContentPane().add(txt_roles, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 190, 30));

        jLabel20.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(153, 153, 153));
        jLabel20.setText("Email");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("No Hp");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, 30));

        txt_nama.setBackground(new java.awt.Color(247, 247, 247));
        txt_nama.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        txt_nama.setBorder(null);
        txt_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_namaActionPerformed(evt);
            }
        });
        txt_nama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_namaKeyPressed(evt);
            }
        });
        getContentPane().add(txt_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 170, 30));

        box_username3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Rounded TextBox.png"))); // NOI18N
        getContentPane().add(box_username3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 210, 50));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, -1));

        txt_username.setBackground(new java.awt.Color(247, 247, 247));
        txt_username.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        txt_username.setBorder(null);
        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });
        txt_username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_usernameKeyPressed(evt);
            }
        });
        getContentPane().add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 170, 30));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Manage User");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        lakilaki.setBackground(new java.awt.Color(247, 247, 247));
        lakilaki.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tick_box_enable_30px.png"))); // NOI18N
        lakilaki.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lakilakiMouseClicked(evt);
            }
        });
        getContentPane().add(lakilaki, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, -1, 30));

        txt_hp.setBackground(new java.awt.Color(247, 247, 247));
        txt_hp.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        txt_hp.setBorder(null);
        txt_hp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hpActionPerformed(evt);
            }
        });
        txt_hp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_hpKeyPressed(evt);
            }
        });
        getContentPane().add(txt_hp, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 170, 30));

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Jenis Kelamin");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, -1, 30));

        jLabel7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel7MouseDragged(evt);
            }
        });
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel7MousePressed(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 66));

        box_username6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Rounded TextBox.png"))); // NOI18N
        getContentPane().add(box_username6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 210, 50));

        perempuan.setBackground(new java.awt.Color(247, 247, 247));
        perempuan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tick_box_disable_26px.png"))); // NOI18N
        perempuan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                perempuanMouseClicked(evt);
            }
        });
        getContentPane().add(perempuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 30, 30));

        box_username2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Rounded TextBox.png"))); // NOI18N
        getContentPane().add(box_username2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 210, 50));

        box_id.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Rounded TextBox.png"))); // NOI18N
        getContentPane().add(box_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 210, 50));

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Password");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Username");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jPanel3.setBackground(new java.awt.Color(247, 247, 247));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_hapus.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_hapus.setForeground(new java.awt.Color(255, 255, 255));
        txt_hapus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_hapus.setText("Hapus");
        jPanel3.add(txt_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 80, 50));

        btn_hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn_action_00000.png"))); // NOI18N
        btn_hapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_hapusMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_hapusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_hapusMouseExited(evt);
            }
        });
        jPanel3.add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 80, 50));

        txt_ubah.setBackground(new java.awt.Color(247, 247, 247));
        txt_ubah.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_ubah.setForeground(new java.awt.Color(255, 255, 255));
        txt_ubah.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_ubah.setText("Ubah");
        jPanel3.add(txt_ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 94, 50));

        btn_ubah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn_action_00000.png"))); // NOI18N
        btn_ubah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ubahMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ubahMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ubahMouseExited(evt);
            }
        });
        jPanel3.add(btn_ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 80, 50));

        txt_tambah.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_tambah.setForeground(new java.awt.Color(255, 255, 255));
        txt_tambah.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_tambah.setText("Tambah");
        jPanel3.add(txt_tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 80, 30));

        btn_tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn_action_00000.png"))); // NOI18N
        btn_tambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_tambahMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_tambahMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_tambahMouseExited(evt);
            }
        });
        jPanel3.add(btn_tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 390, 60));

        jLabel23.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(153, 153, 153));
        jLabel23.setText("Perempuan");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 70, 30));

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("Nama");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        box_username5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Rounded TextBox.png"))); // NOI18N
        getContentPane().add(box_username5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 210, 50));

        jLabel21.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(153, 153, 153));
        jLabel21.setText("Roles");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, 50));

        jLabel24.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(153, 153, 153));
        jLabel24.setText("Alamat");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, -1, 30));

        jLabel22.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(153, 153, 153));
        jLabel22.setText("Laki-laki");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 50, 30));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bg_detail_user_00000_00000.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -30, 540, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    private void txt_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namaActionPerformed

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked

        this.dispose();
    }//GEN-LAST:event_jLabel12MouseClicked

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void lakilakiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lakilakiMouseClicked
        jenis_kelamin = "Laki laki";
        lakilaki.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tick_box_enable_30px.png")));
        perempuan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tick_box_disable_26px.png")));
    }//GEN-LAST:event_lakilakiMouseClicked

    private void txt_hpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hpActionPerformed

    private void txt_alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_alamatActionPerformed

    private void jLabel7MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - mouseX, y - mouseY);
    }//GEN-LAST:event_jLabel7MouseDragged

    private void jLabel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_jLabel7MousePressed

    private void perempuanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_perempuanMouseClicked
        jenis_kelamin = "Perempuan";
        lakilaki.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tick_box_disable_26px.png")));
        perempuan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tick_box_enable_30px.png")));
    }//GEN-LAST:event_perempuanMouseClicked

    private void txt_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passwordActionPerformed

    private void btn_hapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_hapusMouseClicked
        PopUp popup = new PopUp(null, true, "Konfirmasi", "Apakah anda yakin ingin menghapus data?", 0);
        popup.setVisible(true);
        int hasil = popup.hasil();

        if (hasil == 0){
            try{
                String sql ="DELETE FROM detail_akun where username='"+txt_username.getText()+"'";
                String sqll ="DELETE FROM akun where username='"+txt_username.getText()+"'";
                java.sql.Connection conn=auth.Koneksi.configDB();
                java.sql.PreparedStatement pst=conn.prepareStatement(sql);
                java.sql.PreparedStatement pstl=conn.prepareStatement(sqll);
                pst.execute();
                pstl.execute();
                new PopUpMessages(null, true, "Berhasil", "Berhasil menghapus data", 1).setVisible(true);
                this.dispose();
            }catch (Exception e){
                new PopUpMessages(null, true, "Gagal", "Gagal menghapus data", 2).setVisible(true);

            }

        }
    }//GEN-LAST:event_btn_hapusMouseClicked

    private void btn_hapusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_hapusMouseEntered
        btn_hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn_action_hover_00000.png")));
    }//GEN-LAST:event_btn_hapusMouseEntered

    private void btn_hapusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_hapusMouseExited
        btn_hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn_action_00000.png")));
    }//GEN-LAST:event_btn_hapusMouseExited

    private void btn_ubahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ubahMouseClicked
        if ( txt_username.getText().length() > 20 || txt_nama.getText().length() > 30 || txt_username.getText().length() > 20 || txt_password.getText().length() > 20 || txt_alamat.getText().length() > 50 || txt_hp.getText().length() > 13){
            new PopUpMessages(null, true, "Informasi", "Cek panjang length pada tiap Field", 0).setVisible(true);
           
        } else {
            PopUp popup = new PopUp(null, true, "Konfirmasi", "Apakah anda yakin ingin mengubah data?", 0);
            popup.setVisible(true);
            int hasil = popup.hasil();
            if ( hasil == 0 ){
                try{
                    Connection conn = auth.Koneksi.configDB();
                    String jenis_rls = "SELECT id_roles FROM `roles` WHERE jenis_roles = '"+txt_roles.getSelectedItem().toString()+"'";
                    PreparedStatement a = conn.prepareStatement(jenis_rls);
                    ResultSet b = a.executeQuery(jenis_rls);
                    if (b.next()){
                        String id_JenisRoles = b.getString("id_roles");
                        String sqll = "UPDATE akun SET username = '"+txt_username.getText()+"', "
                                + "password = '"+txt_password.getText()+"' "
                                + "WHERE akun.username = '"+this.select_user+"'";
                        String sql = "UPDATE detail_akun SET nama= '"+txt_nama.getText()+"', email = '"
                        +txt_email.getText()+"', nohp = '"
                        +txt_hp.getText()+"', jenis_kelamin = '"
                        +jenis_kelamin+"',alamat = '"
                        +txt_alamat.getText()+"',id_roles = '"
                        +id_JenisRoles+"'WHERE detail_akun.username = '"+txt_username.getText()+"'";
                        java.sql.PreparedStatement pst=conn.prepareStatement(sql);
                        java.sql.PreparedStatement pstl=conn.prepareStatement(sqll);
                        pst.execute();
                        pstl.execute();
                        new PopUpMessages(null, true, "Berhasil", "Berhasil mengubah data", 1).setVisible(true);
                        // update dashboard user

                        if ( saveUser.equals(txt_username.getText())){
                            Dashboard.txt_username.setText(txt_username.getText());
                            Dashboard.txt_email.setText(txt_email.getText());
                            Dashboard.txt_password.setText(txt_password.getText());
                            Dashboard.txt_alamat.setText(txt_alamat.getText());
                            Dashboard.txt_nama.setText(txt_nama.getText());
                            Dashboard.txt_nohp.setText(txt_hp.getText());
                            Dashboard.nama.setText(txt_nama.getText());
                            if(jenis_kelamin.equals("Laki laki")){

                                Dashboard.imgProfile = "/Images/circled_user_male_skin_type_5_100px.png";
                                Dashboard.setJenisKelamin = "Laki laki";
                            } else if ( jenis_kelamin.equals("Perempuan")) {

                                Dashboard.imgProfile = "/Images/circled_user_female_skin_type_4_100px.png";
                                Dashboard.setJenisKelamin = "Perempuan";

                            } else {
                                System.out.println("error");
                            }

                        } else {
                            // kosong
                        }
                        this.dispose();

                    }

                }catch (Exception e){
                    new PopUpMessages(null, true, "Gagal", "Gagal mengubah data", 2).setVisible(true);
                    System.out.println(e);

                }
            } else {

            }
        }
        
    }//GEN-LAST:event_btn_ubahMouseClicked

    private void btn_ubahMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ubahMouseEntered
        btn_ubah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn_action_hover_00000.png")));
    }//GEN-LAST:event_btn_ubahMouseEntered

    private void btn_ubahMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ubahMouseExited
        btn_ubah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn_action_00000.png")));
    }//GEN-LAST:event_btn_ubahMouseExited

    private int setIdAkun;
    
    public void id_akun(){
        try {
         
                String sql = "SELECT id_akun FROM akun WHERE id_akun LIKE '100%' ORDER BY id_akun DESC";
                java.sql.Connection conn=(Connection)auth.Koneksi.configDB();
                java.sql.PreparedStatement ps=conn.prepareStatement(sql);
                java.sql.ResultSet rs = ps.executeQuery(sql);
                if ( rs.next()){
                    String idAkun = rs.getString("id_akun").substring(5);
                    String pertama = String.valueOf(100);
                    String hasil = pertama + "32" + String.valueOf(Integer.parseInt(idAkun)+1);
                    setIdAkun = Integer.parseInt(hasil);

                } else {       
                    setIdAkun = 10032100;   
                }
   
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    
 
    
    private void btn_tambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tambahMouseClicked
        // Tambah data
        if ( txt_username.getText().length() > 20 || txt_nama.getText().length() > 30 || txt_username.getText().length() > 20 || txt_password.getText().length() > 20 || txt_alamat.getText().length() > 50 || txt_hp.getText().length() > 13){
            new PopUpMessages(null, true, "Informasi", "Cek panjang length pada tiap Field", 0).setVisible(true);
           
        } else {
             if(txt_password.getText().equals("") || txt_nama.getText().equals("") || txt_email.getText().equals("")){
            new PopUpMessages(null, true, "Informasi", "Kolom wajib diisi!", 0).setVisible(true);

        } else {
            PopUp popup = new PopUp(null, true, "Konfirmasi", "Apakah anda yakin ingin menambah data?", 0);
            popup.setVisible(true);
            int hasil = popup.hasil();
            if ( hasil == 0 ){
               
                id_akun();
              
                
                try{
                    Connection conn = auth.Koneksi.configDB();
                    String jenis_rls = "SELECT * FROM `roles` WHERE  jenis_roles = '"+txt_roles.getSelectedItem().toString()+"'";
                    PreparedStatement a = conn.prepareStatement(jenis_rls);
                    ResultSet b = a.executeQuery(jenis_rls);
                    if (b.next()){
                        String id_JenisRoles = b.getString("id_roles");
                        String sql = "INSERT INTO akun VALUES ("+setIdAkun+", '"+txt_username.getText()+"','"
                                        +txt_password.getText()+"')";
                        String sqll = "INSERT INTO detail_akun VALUES ('"+txt_username.getText()+"','"
                                        +txt_nama.getText()+"','"
                                        +txt_email.getText()+"','"
                                        +txt_hp.getText()+"','"
                                        +jenis_kelamin+"','"
                                        +txt_alamat.getText()+"','"
                                        +id_JenisRoles+"')";
                        java.sql.PreparedStatement pst=conn.prepareStatement(sql);
                        java.sql.PreparedStatement pstl= conn.prepareStatement(sqll);
                        pst.execute();
                        pstl.execute();
                        new PopUpMessages(null, true, "Berhasil", "Berhasil Menambahkan Data", 1).setVisible(true);
                        
                        this.dispose();

                    }

                } catch (Exception e){
                    System.out.println(e);
                    new PopUpMessages(null, true, "Gagal", "Gagal menambahkan data", 2).setVisible(true);
                }
            } else {
            }
        }
        }
        
        
       
    }//GEN-LAST:event_btn_tambahMouseClicked

    private void btn_tambahMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tambahMouseEntered
        btn_tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn_action_hover_00000.png")));
    }//GEN-LAST:event_btn_tambahMouseEntered

    private void btn_tambahMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tambahMouseExited
        btn_tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn_action_00000.png")));
    }//GEN-LAST:event_btn_tambahMouseExited

    private void txt_usernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_usernameKeyPressed
       
    }//GEN-LAST:event_txt_usernameKeyPressed

    private void txt_passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passwordKeyPressed
      
    }//GEN-LAST:event_txt_passwordKeyPressed

    private void txt_namaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_namaKeyPressed
      
    }//GEN-LAST:event_txt_namaKeyPressed

    private void txt_emailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_emailKeyPressed
    
    }//GEN-LAST:event_txt_emailKeyPressed

    private void txt_alamatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_alamatKeyPressed
     
    }//GEN-LAST:event_txt_alamatKeyPressed

    private void txt_hpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_hpKeyPressed
     
    }//GEN-LAST:event_txt_hpKeyPressed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ESCAPE){
                this.konfirm = 1;
                this.dispose();
                 
             } else {
                 
             }
    }//GEN-LAST:event_formKeyPressed

    private void txt_rolesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_rolesMouseClicked
        
    }//GEN-LAST:event_txt_rolesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Detail_Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Detail_Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Detail_Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Detail_Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Detail_Users dialog = new Detail_Users(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    int mouseX;
    int mouseY;
    public static String saveUser;
    public String jenis_kelamin = "Laki laki";
    public String select_user;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel box_id;
    private javax.swing.JLabel box_username2;
    private javax.swing.JLabel box_username3;
    private javax.swing.JLabel box_username4;
    private javax.swing.JLabel box_username5;
    private javax.swing.JLabel box_username6;
    private javax.swing.JLabel btn_hapus;
    private javax.swing.JLabel btn_tambah;
    private javax.swing.JLabel btn_ubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JCheckBox lakilaki;
    public static javax.swing.JCheckBox perempuan;
    private javax.swing.JTextField txt_alamat;
    private javax.swing.JTextField txt_email;
    private javax.swing.JLabel txt_hapus;
    private javax.swing.JTextField txt_hp;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_password;
    private javax.swing.JComboBox<String> txt_roles;
    private javax.swing.JLabel txt_tambah;
    private javax.swing.JLabel txt_ubah;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
