package src;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



/**
 *
 * @author Mphstar
 */
public class Form_Login extends javax.swing.JFrame {
 
    /**
     * Creates new form Form_Login
     */
    
    
    public Form_Login() {
        this.setResizable(false);
        initComponents();
        //this.setSize(Toolkit.getDefaultToolkit().getScreenSize());
  
    }
    
    public void dataAkun(){
        try {
            Connection conn = auth.Koneksi.configDB();
            String sql = "SELECT akun.username, akun.password, detail_akun.nama,"
                    + " detail_akun.email, detail_akun.nohp, detail_akun.jenis_kelamin,"
                    + " detail_akun.alamat, roles.jenis_roles FROM akun JOIN detail_akun "
                    + "ON akun.username = detail_akun.username JOIN roles ON detail_akun.id_roles = roles.id_roles WHERE detail_akun.username = '"+txt_username.getText()+"'";
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery(sql);
            if(rs.next()){
    
                Dashboard.txt_username.setText(rs.getString("username"));
                Dashboard.txt_email.setText(rs.getString("email"));
                Dashboard.txt_password.setText(rs.getString("password"));
                Dashboard.txt_alamat.setText(rs.getString("alamat"));
                Dashboard.txt_nama.setText(rs.getString("nama"));
                Dashboard.txt_nohp.setText(rs.getString("nohp"));
                Dashboard.nama.setText(rs.getString("nama"));
                if(rs.getString("jenis_kelamin").toString().equals("Laki laki")){
                    
                    Dashboard.setJenisKelamin = "Laki laki";
                    Dashboard.imgProfile = "/Images/circled_user_male_skin_type_5_100px.png";
//                            Dashboard.iconfoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/circled_user_male_skin_type_5_100px.png")));
//                            Dashboard.lakilaki.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tick_box_enable_30px.png")));
//                            Dashboard.perempuan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tick_box_disable_26px.png")));
//                      
                    
                } else if (rs.getString("jenis_kelamin").toString().equals("Perempuan")) {
                    
                    
                    Dashboard.setJenisKelamin = "Perempuan";
                        Dashboard.imgProfile = "/Images/circled_user_female_skin_type_4_100px.png";
//                            Dashboard.perempuan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tick_box_enable_30px.png")));
//                            Dashboard.lakilaki.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tick_box_disable_26px.png")));
//                            Dashboard.iconfoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/circled_user_female_skin_type_4_100px.png")));
//                    
                } else {
                    System.out.println("error");
                }
                // check roles
                if(rs.getString("jenis_roles").equals("admin")){
                    Riwayat.panel_hapus.setVisible(true);
        
                    Riwayat.nilai_opsi = 0;
                    Dashboard.checkRoles = 0;
                    
                } else {
                    Riwayat.panel_hapus.setVisible(false);
       
                    Dashboard.checkRoles = 1;
                    Riwayat.nilai_opsi = 1;
                }
                
            }
        } catch (Exception e) {
            e.getMessage();
        }
    }
    
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        box_username = new javax.swing.JLabel();
        box_password = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        check_pw = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Toko SA");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Images/icon.png")).getImage());
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        jLabel1.setText("Login");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 140, 170, -1));

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("LOGIN");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 390, 110, 30));

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel2.setText("Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 299, -1, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel3.setText("Username");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 229, -1, -1));

        txt_username.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        txt_username.setBorder(null);
        getContentPane().add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 259, 170, 30));

        txt_password.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        txt_password.setBorder(null);
        txt_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passwordActionPerformed(evt);
            }
        });
        getContentPane().add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 329, 170, 30));

        box_username.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Rounded TextBox.png"))); // NOI18N
        getContentPane().add(box_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 319, 220, 50));

        box_password.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Rounded TextBox.png"))); // NOI18N
        getContentPane().add(box_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 249, 220, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Rounded Button.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 379, 210, 50));

        check_pw.setBackground(new java.awt.Color(255, 255, 255));
        check_pw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/hide.png"))); // NOI18N
        check_pw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_pwActionPerformed(evt);
            }
        });
        getContentPane().add(check_pw, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 329, -1, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bg_login_00000.png"))); // NOI18N
        jLabel9.setMaximumSize(new java.awt.Dimension(1920, 1080));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 609));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void check_pwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_pwActionPerformed
        if (check_pw.isSelected()){
            check_pw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/unhide.png")));
            txt_password.setEchoChar((char)0);
            
        } else {
            check_pw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/hide.png")));
            txt_password.setEchoChar('*');
        }

    }//GEN-LAST:event_check_pwActionPerformed

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Rounded Button Hover.png")));
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Rounded Button.png")));
    }//GEN-LAST:event_jLabel6MouseExited

    private void login(){
        if ( txt_username.getText().equals("")|| txt_password.getText().equals("")){
            new PopUpMessages(this, true, "Informasi", "Username dan Password wajib diisi", 0).setVisible(true);
        } else {
            try {
                String sql = "SELECT * FROM akun WHERE username='"+txt_username.getText()
                            +"'AND password='"+txt_password.getText()+"'";
                java.sql.Connection conn= auth.Koneksi.configDB();
                java.sql.PreparedStatement pst=conn.prepareStatement(sql);
              
                java.sql.ResultSet rs = pst.executeQuery(sql);
                if (rs.next()){
                    if (txt_username.getText().equals(rs.getString("username"))
                        && txt_password.getText().equals(rs.getString("password"))){
                        dataAkun();
                        PopUpMessages sukses = new PopUpMessages(this, true, "Berhasil", "Login Berhasil", 1);
                        
                        sukses.setVisible(true);
                        
                        //this.setVisible(false);
                        this.dispose();
                        
                        Dashboard menu = new Dashboard();
                        
                        menu.setVisible(true);
                        
                        
                        Detail_Users.saveUser = txt_username.getText();
                        String usernamenya = txt_username.getText();
                        Dashboard.username.setText(usernamenya);
                        Pembelian_Barang.username = usernamenya;
                    } 
                } else {
                        new PopUpMessages(this, true, "Gagal", "Username atau Password salah", 2).setVisible(true);
                        txt_password.setText("");
                    }
            } catch (SQLException ex) {
                ex.getMessage();
            }
        }
    }
    
    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        login();
        
        
        
       
    }//GEN-LAST:event_jLabel6MouseClicked

    private void txt_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passwordActionPerformed
        login();
    }//GEN-LAST:event_txt_passwordActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       PopUp popup = new PopUp(this, true, "Konfirmasi", "Apakah anda yakin ingin keluar?", 0);
        popup.setVisible(true);
        int hasil = popup.hasil();
        
        if(hasil == 0){
            this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        } else {
            this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              Form_Login login = new Form_Login();
              login.setVisible(true);
             
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel box_password;
    private javax.swing.JLabel box_username;
    private javax.swing.JCheckBox check_pw;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
