/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.FileWriter;
import java.io.RandomAccessFile;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.UIManager;

/**
 *
 * @author Mphstar
 */
public class KonfigurasiDatabase extends javax.swing.JDialog {

    /**
     * Creates new form Detail_Users
     */
    
    public void UI(){
        //setUI(new ModernScrollBarUI());
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()){
                if ("Windows".equals(info.getName())){
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception e) {
            e.getMessage();
        }
    }
    
    public KonfigurasiDatabase(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.getRootPane().setOpaque(false);
        this.getContentPane ().setBackground (new Color (0, 0, 0, 0));
        this.setBackground (new Color (0, 0, 0, 0));
  
    }
    
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        txt_pw = new javax.swing.JTextField();
        txt_port = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        box_username3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_url = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_database = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        box_username6 = new javax.swing.JLabel();
        box_username2 = new javax.swing.JLabel();
        box_id = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txt_tambah = new javax.swing.JLabel();
        btn_tambah = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        box_username5 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        label = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Toko SA");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Images/icon.png")).getImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setForeground(new java.awt.Color(102, 102, 102));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 420, 1));

        txt_pw.setBackground(new java.awt.Color(247, 247, 247));
        txt_pw.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        txt_pw.setText("null");
        txt_pw.setBorder(null);
        txt_pw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pwActionPerformed(evt);
            }
        });
        txt_pw.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_pwKeyPressed(evt);
            }
        });
        getContentPane().add(txt_pw, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 170, 30));

        txt_port.setBackground(new java.awt.Color(247, 247, 247));
        txt_port.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        txt_port.setText("3306");
        txt_port.setBorder(null);
        txt_port.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_portActionPerformed(evt);
            }
        });
        txt_port.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_portKeyPressed(evt);
            }
        });
        getContentPane().add(txt_port, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 170, 30));

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Nama Database");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, 40));

        txt_username.setBackground(new java.awt.Color(247, 247, 247));
        txt_username.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        txt_username.setText("root");
        txt_username.setBorder(null);
        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });
        txt_username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_usernameKeyPressed(evt);
            }
        });
        getContentPane().add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 170, 30));

        box_username3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Rounded TextBox.png"))); // NOI18N
        getContentPane().add(box_username3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 210, 50));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, -1));

        txt_url.setBackground(new java.awt.Color(247, 247, 247));
        txt_url.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        txt_url.setText("localhost");
        txt_url.setBorder(null);
        txt_url.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_urlActionPerformed(evt);
            }
        });
        txt_url.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_urlKeyPressed(evt);
            }
        });
        getContentPane().add(txt_url, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 170, 30));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Konfigurasi Database");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        txt_database.setBackground(new java.awt.Color(247, 247, 247));
        txt_database.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        txt_database.setText("tokosa");
        txt_database.setBorder(null);
        txt_database.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_databaseActionPerformed(evt);
            }
        });
        txt_database.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_databaseKeyPressed(evt);
            }
        });
        getContentPane().add(txt_database, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 170, 30));

        jLabel7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel7MouseDragged(evt);
            }
        });
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel7MousePressed(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 66));

        box_username6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Rounded TextBox.png"))); // NOI18N
        getContentPane().add(box_username6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 210, 70));

        box_username2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Rounded TextBox.png"))); // NOI18N
        getContentPane().add(box_username2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 210, 50));

        box_id.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Rounded TextBox.png"))); // NOI18N
        getContentPane().add(box_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 210, 50));

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Port");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Url");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jPanel3.setBackground(new java.awt.Color(247, 247, 247));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_tambah.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_tambah.setForeground(new java.awt.Color(255, 255, 255));
        txt_tambah.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_tambah.setText("Konfirmasi");
        jPanel3.add(txt_tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 80, 30));

        btn_tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn_action_00000.png"))); // NOI18N
        btn_tambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_tambahMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_tambahMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_tambahMouseExited(evt);
            }
        });
        jPanel3.add(btn_tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 390, 60));

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("Username");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        box_username5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Rounded TextBox.png"))); // NOI18N
        getContentPane().add(box_username5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 210, 50));

        jLabel24.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(153, 153, 153));
        jLabel24.setText("Password");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, 30));

        label.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        label.setText("* Masukkan null jika password kosong.");
        getContentPane().add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bg_detail_user_00000_00000.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -30, 540, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked

        System.exit(0);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void txt_urlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_urlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_urlActionPerformed

    private void txt_databaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_databaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_databaseActionPerformed

    private void txt_pwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pwActionPerformed

    private void jLabel7MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - mouseX, y - mouseY);
    }//GEN-LAST:event_jLabel7MouseDragged

    private void jLabel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_jLabel7MousePressed

    private void txt_portActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_portActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_portActionPerformed

    private void btn_tambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tambahMouseClicked
        System.out.println("aaa");
        if(txt_database.getText().equals("")||txt_port.getText().equals("")||txt_pw.getText().equals("")||txt_url.getText().equals("")||txt_username.getText().equals("")){
            new PopUpMessages(null, true, "Informasi", "Data Wajib diisi!", 0).setVisible(true);
        } else {
            if(txt_port.getText().matches("[0-9]*")){
                
                try {
                   FileWriter fw = new FileWriter("konfigurasi.txt");
                    
                    RandomAccessFile raf = new RandomAccessFile("konfigurasi.txt", "rw");
                    raf.writeBytes("Url : " +txt_url.getText()+ "\r\n");
                    raf.writeBytes("Database : " +txt_database.getText()+ "\r\n");
                    raf.writeBytes("Port : " +txt_port.getText()+ "\r\n");
                    raf.writeBytes("User : " +txt_username.getText()+ "\r\n");
                    raf.writeBytes("Password : " +txt_pw.getText()+ "\r\n\r\n");
                    raf.writeBytes("// masukkan null pada password jika kosong");
                    new PopUpMessages(null, true, "Berhasil", "Konfigurasi berhasil", 1).setVisible(true);
                    this.dispose();
                    new Main();
                } catch (Exception e) {
                    
                    System.out.println(e);
                }
            } else {
                new PopUpMessages(null, true, "Gagal", "Port harus berupa angka", 0).setVisible(true);
            }
        }
    }//GEN-LAST:event_btn_tambahMouseClicked

    private void btn_tambahMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tambahMouseEntered
        btn_tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn_action_hover_00000.png")));
    }//GEN-LAST:event_btn_tambahMouseEntered

    private void btn_tambahMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tambahMouseExited
        btn_tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn_action_00000.png")));
    }//GEN-LAST:event_btn_tambahMouseExited

    private void txt_urlKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_urlKeyPressed
       
    }//GEN-LAST:event_txt_urlKeyPressed

    private void txt_portKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_portKeyPressed
      
    }//GEN-LAST:event_txt_portKeyPressed

    private void txt_usernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_usernameKeyPressed
      
    }//GEN-LAST:event_txt_usernameKeyPressed

    private void txt_pwKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pwKeyPressed
    
    }//GEN-LAST:event_txt_pwKeyPressed

    private void txt_databaseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_databaseKeyPressed
       
    }//GEN-LAST:event_txt_databaseKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KonfigurasiDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KonfigurasiDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KonfigurasiDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KonfigurasiDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                KonfigurasiDatabase dialog = new KonfigurasiDatabase(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    int mouseX;
    int mouseY;
    public static String saveUser;
    public String jenis_kelamin = "Laki laki";
    public String select_user;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel box_id;
    private javax.swing.JLabel box_username2;
    private javax.swing.JLabel box_username3;
    private javax.swing.JLabel box_username5;
    private javax.swing.JLabel box_username6;
    private javax.swing.JLabel btn_tambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel label;
    private javax.swing.JTextField txt_database;
    private javax.swing.JTextField txt_port;
    private javax.swing.JTextField txt_pw;
    private javax.swing.JLabel txt_tambah;
    private javax.swing.JTextField txt_url;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
